wish_visit = ['korea', 'china', 'norway', 'iceland', 'greece']
print(wish_visit)
print(sorted(wish_visit))
print(wish_visit)
print(sorted(wish_visit, reverse=True))
print(wish_visit)
wish_visit.reverse()
print(wish_visit)
wish_visit.reverse()
print(wish_visit)
wish_visit.sort()
print(wish_visit)
wish_visit.sort(reverse=True)
print(wish_visit)